"""会话持久化层（对齐官方架构 B: StorageBackedSession + SessionRepo）。

- A0：纯函数层——类型模型、id 生成、侧存储地址、序列化。
- A1：存储契约层——Storage Protocol、完整 Write 联合、提交管线、InMemoryStorage。
- A2：SqliteStorage——落盘后端，SQL 直查，事务化 commit + 聚合行。
Session / SessionRepo 等在后续切片加入。
"""

from __future__ import annotations

from .compaction import (
    CutPointResult,
    build_compaction_entry,
    collect_retained_tail,
    find_cut_point,
    find_turn_start_index,
    find_valid_cut_points,
)
from .context import (
    EntryProjector,
    build_context_entries,
    build_session_context,
    is_context_message,
    session_entry_to_context_messages,
)
from .errors import CompactionRaceError, SessionCorruptError, SessionError
from .factory import AgentSession, Summarize, create_agent_session
from .ids import assert_valid_session_id, new_entry_id, new_session_id
from .repo import InMemorySessionRepo, SessionRepo, SqliteSessionRepo
from .serialize import (
    entry_from_dict,
    entry_to_dict,
    message_from_dict,
    message_to_dict,
)
from .session import (
    DEFAULT_BRANCH,
    MutationLine,
    SessionBranchExistsError,
    SessionClosedError,
    SessionInvalidBranchError,
    SessionInvariantError,
    SessionMetadata,
    SessionMutation,
    SessionPendingAssistantMessageError,
    SessionUnknownTargetError,
    StorageBackedBranch,
    StorageBackedSession,
)
from .storage import (
    STORAGE_VERSION,
    BranchScan,
    CommitError,
    CommitResult,
    CommittedEntryWrite,
    CommittedListWrite,
    CommittedUsageWrite,
    CommittedValueWrite,
    CommittedWrite,
    Context,
    EntryCursor,
    EntryScan,
    EntryStructure,
    EntryWrite,
    InMemoryStorage,
    InMemoryStorageState,
    PreparedCommit,
    SessionStats,
    SqliteStorage,
    Storage,
    UsageRow,
    UsageScan,
    UsageWrite,
    Write,
    add_usage,
    commit_write,
    committed_seq,
    insert_entry,
    insert_usage,
    prepare_storage_commit,
    validate_committed_writes,
)
from .types import (
    BranchSummaryEntry,
    CompactionEntry,
    CustomEntry,
    Entry,
    EntryBase,
    EntryType,
    JsonValue,
    MessageEntry,
    NewEntry,
)
from .values import (
    ListAppendWrite,
    ListCursor,
    ListDeleteWrite,
    ListElement,
    ListReadOptions,
    ListWrite,
    ResolvedListReadOptions,
    StoredValue,
    Value,
    ValueDeleteWrite,
    ValueList,
    ValueSetWrite,
    ValueWrite,
    append_list,
    branch_tip,
    delete_list,
    delete_value,
    entry_label,
    lane_config,
    list_,
    resolve_list_read_options,
    session_name,
    set_value,
    value,
)
from .values import Write as SideWrite

__all__ = [
    # errors
    "SessionError",
    "SessionCorruptError",
    "CompactionRaceError",
    # ids
    "new_session_id",
    "new_entry_id",
    "assert_valid_session_id",
    # types
    "EntryType",
    "JsonValue",
    "EntryBase",
    "MessageEntry",
    "CompactionEntry",
    "BranchSummaryEntry",
    "CustomEntry",
    "Entry",
    "NewEntry",
    # serialize
    "entry_to_dict",
    "entry_from_dict",
    "message_to_dict",
    "message_from_dict",
    # values
    "Value",
    "ValueList",
    "StoredValue",
    "ListElement",
    "ListCursor",
    "ListReadOptions",
    "ResolvedListReadOptions",
    "resolve_list_read_options",
    "ValueSetWrite",
    "ValueDeleteWrite",
    "ListAppendWrite",
    "ListDeleteWrite",
    "ValueWrite",
    "ListWrite",
    "SideWrite",
    "value",
    "list_",
    "set_value",
    "delete_value",
    "append_list",
    "delete_list",
    "lane_config",
    "branch_tip",
    "session_name",
    "entry_label",
    # storage_types
    "Context",
    "Storage",
    "Write",
    "EntryWrite",
    "UsageWrite",
    "UsageRow",
    "CommitResult",
    "SessionStats",
    "EntryStructure",
    "EntryCursor",
    "BranchScan",
    "EntryScan",
    "UsageScan",
    # commit
    "CommitError",
    "CommittedEntryWrite",
    "CommittedUsageWrite",
    "CommittedValueWrite",
    "CommittedListWrite",
    "CommittedWrite",
    "PreparedCommit",
    "insert_entry",
    "insert_usage",
    "commit_write",
    "committed_seq",
    "prepare_storage_commit",
    "validate_committed_writes",
    "add_usage",
    # memory
    "InMemoryStorage",
    "InMemoryStorageState",
    # sqlite
    "SqliteStorage",
    "STORAGE_VERSION",
    # context
    "EntryProjector",
    "build_context_entries",
    "session_entry_to_context_messages",
    "build_session_context",
    "is_context_message",
    # session
    "DEFAULT_BRANCH",
    "MutationLine",
    "SessionMetadata",
    "SessionMutation",
    "StorageBackedBranch",
    "StorageBackedSession",
    "SessionInvariantError",
    "SessionInvalidBranchError",
    "SessionBranchExistsError",
    "SessionPendingAssistantMessageError",
    "SessionUnknownTargetError",
    "SessionClosedError",
    # repo
    "SessionRepo",
    "InMemorySessionRepo",
    "SqliteSessionRepo",
    # factory (A4)
    "AgentSession",
    "Summarize",
    "create_agent_session",
    # session compaction (D2)
    "CutPointResult",
    "find_valid_cut_points",
    "find_turn_start_index",
    "find_cut_point",
    "collect_retained_tail",
    "build_compaction_entry",
]
